name: Generate README

on:
  pull-request:

jobs:
  generate_readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install nbconvert
          pip install black_nbconvert
          pip install markupsafe==2.0.1
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Clear and format Jupyter Notebook output
        run: |
          jupyter nbconvert --clear-output --inplace *.ipynb
          black_nbconvert .

      - name: Convert README ipynb to md
        run: |
          rm -rf README_files
          jupyter nbconvert --to markdown --execute README.ipynb
